import type { ChapterId } from '../campaign/campaignTypes';
import type { LocalizedText } from '../journey/sceneTypes';
import type { ModuleId } from '../my-ai/capabilityTypes';
import type { ConceptGraphEdge, KnowledgeConcept } from './conceptTypes';

const text = (ru: string, en: string): LocalizedText => ({ ru, en });

interface ConceptSeed {
  id: string;
  ru: string;
  en: string;
  chapter: ChapterId;
  whyRu: string;
  whyEn: string;
  intuitionRu: string;
  intuitionEn: string;
  formal?: string;
  code?: string;
  moduleId?: ModuleId;
  related?: string[];
  replay?: string;
}

const seed = (value: ConceptSeed): KnowledgeConcept => ({
  id: value.id,
  label: text(value.ru, value.en),
  chapterId: value.chapter,
  why: text(value.whyRu, value.whyEn),
  intuition: text(value.intuitionRu, value.intuitionEn),
  formal: text(value.intuitionRu, value.intuitionEn),
  example: text(`Лабораторный пример: ${value.whyRu}`, `Lab example: ${value.whyEn}`),
  ...(value.formal ? { math: value.formal } : {}),
  ...(value.code ? { code: value.code } : {}),
  ...(value.moduleId ? { moduleId: value.moduleId } : {}),
  related: value.related ?? [],
  ...(value.replay ? { replaySceneId: value.replay } : {}),
});

const seeds: ConceptSeed[] = [
  { id: 'intelligence-not-computation', ru: 'Интеллект ≠ вычисление', en: 'Intelligence ≠ computation', chapter: 'initialization', whyRu: 'Скорость калькулятора не объясняет адаптацию.', whyEn: 'Calculator speed does not explain adaptation.', intuitionRu: 'Интеллект проявляется в использовании информации и изменении поведения.', intuitionEn: 'Intelligence appears in using information and changing behavior.', related: ['data'] },
  { id: 'data', ru: 'Данные', en: 'Data', chapter: 'initialization', whyRu: 'Машине нужен наблюдаемый материал.', whyEn: 'A machine needs observable material.', intuitionRu: 'Данные — значения до их интерпретации.', intuitionEn: 'Data are values before interpretation.', moduleId: 'data-interface', related: ['feature', 'representation'], replay: 'l3-context' },
  { id: 'feature', ru: 'Признак', en: 'Feature', chapter: 'initialization', whyRu: 'Не каждый измеряемый факт полезен для задачи.', whyEn: 'Not every measurable fact helps the task.', intuitionRu: 'Признак — выбранное свойство объекта.', intuitionEn: 'A feature is a selected property of an object.', moduleId: 'feature-system', related: ['data', 'representation', 'weight'], replay: 'l4-select' },
  { id: 'representation', ru: 'Представление', en: 'Representation', chapter: 'initialization', whyRu: 'Компьютеру нужна операциональная форма объекта.', whyEn: 'A computer needs an operational form of an object.', intuitionRu: 'Представление переводит объект в структуру чисел.', intuitionEn: 'A representation maps an object into a numeric structure.', moduleId: 'representation-layer', related: ['feature', 'parameter', 'embedding'], replay: 'l5-representation' },
  { id: 'rule', ru: 'Правило', en: 'Rule', chapter: 'decision-engine', whyRu: 'Нужно связать вход с действием.', whyEn: 'Input must be connected to action.', intuitionRu: 'Правило явно задаёт условие и результат.', intuitionEn: 'A rule explicitly states a condition and outcome.', moduleId: 'rule-engine', related: ['parameter', 'prediction'] },
  { id: 'parameter', ru: 'Параметр', en: 'Parameter', chapter: 'decision-engine', whyRu: 'Системе нужна настраиваемая часть поведения.', whyEn: 'A system needs adjustable behavior.', intuitionRu: 'Параметр — число, которое модель изменяет или хранит.', intuitionEn: 'A parameter is a number a model stores or changes.', moduleId: 'parameter-unit', related: ['weight', 'bias', 'gradient'], replay: 'c2-experiment' },
  { id: 'weight', ru: 'Вес', en: 'Weight', chapter: 'decision-engine', whyRu: 'Признаки влияют на решение неодинаково.', whyEn: 'Features do not influence a decision equally.', intuitionRu: 'Weight задаёт силу и направление влияния.', intuitionEn: 'A weight sets influence strength and direction.', formal: 'y = wx + b', code: 'const y = x * w + b;', related: ['feature', 'bias', 'prediction'] },
  { id: 'bias', ru: 'Смещение', en: 'Bias', chapter: 'decision-engine', whyRu: 'Нужен базовый ответ при нулевом входе.', whyEn: 'A baseline response is needed at zero input.', intuitionRu: 'Bias сдвигает всю функцию.', intuitionEn: 'A bias shifts the whole function.', formal: 'y(0) = b', related: ['weight', 'prediction'] },
  { id: 'prediction', ru: 'Прогноз', en: 'Prediction', chapter: 'decision-engine', whyRu: 'Модель должна выдать проверяемый результат.', whyEn: 'A model must produce a testable result.', intuitionRu: 'Prediction — вычисленный ответ до сравнения с target.', intuitionEn: 'A prediction is the computed answer before comparison with a target.', moduleId: 'prediction-head', related: ['target', 'loss'] },
  { id: 'target', ru: 'Цель', en: 'Target', chapter: 'learning-protocol', whyRu: 'Нужен эталон для проверки prediction.', whyEn: 'A reference is needed to check a prediction.', intuitionRu: 'Target — желаемый ответ в обучающем примере.', intuitionEn: 'A target is the desired answer in a training example.', related: ['prediction', 'error'] },
  { id: 'error', ru: 'Ошибка', en: 'Error', chapter: 'learning-protocol', whyRu: 'Нужно знать направление несовпадения.', whyEn: 'The mismatch direction must be known.', intuitionRu: 'Error сравнивает prediction и target.', intuitionEn: 'Error compares a prediction and a target.', formal: 'e = ŷ - y', related: ['target', 'loss'] },
  { id: 'loss', ru: 'Функция потерь', en: 'Loss function', chapter: 'learning-protocol', whyRu: 'Одним числом нужно оценить качество модели.', whyEn: 'Model quality needs one measurable number.', intuitionRu: 'Loss превращает ошибки примеров в цель оптимизации.', intuitionEn: 'Loss turns example errors into an optimization objective.', formal: 'MSE = (1/n)Σ(ŷᵢ-yᵢ)²', moduleId: 'loss-analyzer', related: ['error', 'gradient'], replay: 'c3-experiment' },
  { id: 'gradient', ru: 'Градиент', en: 'Gradient', chapter: 'learning-protocol', whyRu: 'Нужно выбрать направление изменения параметров.', whyEn: 'A direction for parameter change is needed.', intuitionRu: 'Gradient показывает, куда loss растёт быстрее всего.', intuitionEn: 'A gradient points where loss rises fastest.', formal: '∇L(θ)', moduleId: 'gradient-engine', related: ['loss', 'learning-rate', 'gradient-descent'] },
  { id: 'learning-rate', ru: 'Скорость обучения', en: 'Learning rate', chapter: 'learning-protocol', whyRu: 'Шаг обновления может быть слишком слабым или разрушительным.', whyEn: 'An update can be too weak or destructive.', intuitionRu: 'Learning rate задаёт длину шага по параметрам.', intuitionEn: 'The learning rate sets parameter step size.', formal: 'θ ← θ - η∇L', related: ['gradient', 'optimizer'] },
  { id: 'gradient-descent', ru: 'Градиентный спуск', en: 'Gradient descent', chapter: 'learning-protocol', whyRu: 'Loss нужно уменьшать повторяемым алгоритмом.', whyEn: 'Loss must be reduced by a repeatable algorithm.', intuitionRu: 'Алгоритм делает небольшие шаги против gradient.', intuitionEn: 'The algorithm makes small steps against the gradient.', moduleId: 'optimizer', related: ['gradient', 'learning-rate'] },
  { id: 'neuron', ru: 'Нейрон', en: 'Neuron', chapter: 'neural-core', whyRu: 'Нужен повторяемый вычислительный элемент.', whyEn: 'A repeatable compute element is needed.', intuitionRu: 'Нейрон объединяет inputs, weights, bias и activation.', intuitionEn: 'A neuron combines inputs, weights, a bias, and an activation.', formal: 'y = φ(Wx+b)', moduleId: 'neuron', related: ['activation', 'layer'], replay: 'c4-experiment' },
  { id: 'activation', ru: 'Активация', en: 'Activation', chapter: 'neural-core', whyRu: 'Без нелинейности слои схлопываются в одну линейную функцию.', whyEn: 'Without nonlinearity, layers collapse into one linear function.', intuitionRu: 'Activation изгибает пространство решений.', intuitionEn: 'An activation bends the decision space.', formal: 'ReLU(x)=max(0,x)', moduleId: 'activation', related: ['neuron', 'hidden-layer'] },
  { id: 'layer', ru: 'Слой', en: 'Layer', chapter: 'neural-core', whyRu: 'Одновременно нужны несколько новых признаков.', whyEn: 'Several new features are needed at once.', intuitionRu: 'Слой применяет группу нейронов к одному состоянию.', intuitionEn: 'A layer applies a group of neurons to one state.', moduleId: 'layer-stack', related: ['neuron', 'hidden-layer'] },
  { id: 'hidden-layer', ru: 'Скрытый слой', en: 'Hidden layer', chapter: 'neural-core', whyRu: 'XOR нельзя разделить одной прямой.', whyEn: 'XOR cannot be separated by one line.', intuitionRu: 'Hidden layer строит промежуточное представление.', intuitionEn: 'A hidden layer builds an intermediate representation.', related: ['xor', 'backpropagation'] },
  { id: 'backpropagation', ru: 'Обратное распространение', en: 'Backpropagation', chapter: 'neural-core', whyRu: 'Каждый параметр сети должен получить свой gradient.', whyEn: 'Every network parameter needs its own gradient.', intuitionRu: 'Backprop применяет chain rule от loss назад по графу.', intuitionEn: 'Backprop applies the chain rule from loss backward through the graph.', moduleId: 'backpropagation', related: ['gradient', 'layer'] },
  { id: 'xor', ru: 'XOR', en: 'XOR', chapter: 'neural-core', whyRu: 'Это минимальная нелинейная проверка архитектуры.', whyEn: 'It is a minimal nonlinear architecture test.', intuitionRu: 'Ответ истинен, когда входы различаются.', intuitionEn: 'The answer is true when inputs differ.', related: ['hidden-layer', 'activation'] },
  { id: 'token', ru: 'Токен', en: 'Token', chapter: 'text-lab', whyRu: 'Текст нужно разбить на вычислимые части.', whyEn: 'Text must be split into computable pieces.', intuitionRu: 'Token — единица последовательности для модели.', intuitionEn: 'A token is a sequence unit for a model.', related: ['vocabulary', 'tokenizer'] },
  { id: 'vocabulary', ru: 'Словарь', en: 'Vocabulary', chapter: 'text-lab', whyRu: 'Каждый token должен иметь стабильный ID.', whyEn: 'Every token needs a stable ID.', intuitionRu: 'Vocabulary сопоставляет tokens и integer IDs.', intuitionEn: 'A vocabulary maps tokens to integer IDs.', moduleId: 'vocabulary', related: ['token', 'bpe'] },
  { id: 'bpe', ru: 'BPE', en: 'BPE', chapter: 'text-lab', whyRu: 'Слова бесконечны, а vocabulary ограничен.', whyEn: 'Words are unbounded while a vocabulary is finite.', intuitionRu: 'BPE многократно объединяет частые соседние части.', intuitionEn: 'BPE repeatedly merges frequent adjacent pieces.', related: ['token', 'vocabulary'] },
  { id: 'tokenizer', ru: 'Токенизатор', en: 'Tokenizer', chapter: 'text-lab', whyRu: 'Нужен воспроизводимый перевод текста в IDs.', whyEn: 'Text needs a reproducible mapping to IDs.', intuitionRu: 'Tokenizer кодирует и декодирует последовательности.', intuitionEn: 'A tokenizer encodes and decodes sequences.', moduleId: 'tokenizer', related: ['token', 'vocabulary'], replay: 'c5-experiment' },
  { id: 'embedding', ru: 'Embedding', en: 'Embedding', chapter: 'text-lab', whyRu: 'Token ID не несёт геометрического смысла.', whyEn: 'A token ID has no geometric meaning.', intuitionRu: 'Embedding заменяет ID обучаемым vector.', intuitionEn: 'An embedding replaces an ID with a trainable vector.', formal: 'xₜ = E[tokenₜ]', moduleId: 'embedding-space', related: ['representation', 'attention'] },
  { id: 'position', ru: 'Позиция', en: 'Position', chapter: 'context', whyRu: 'Attention без позиции не различает порядок.', whyEn: 'Attention without position cannot distinguish order.', intuitionRu: 'Position signal отмечает место token в sequence.', intuitionEn: 'A position signal marks a token place in a sequence.', moduleId: 'position-encoder', related: ['rope', 'attention'] },
  { id: 'rope', ru: 'RoPE', en: 'RoPE', chapter: 'context', whyRu: 'Отношение позиций важнее абсолютного номера.', whyEn: 'Relative position matters more than an absolute index.', intuitionRu: 'RoPE поворачивает Query и Key в зависимости от позиции.', intuitionEn: 'RoPE rotates Queries and Keys according to position.', related: ['position', 'query', 'key'] },
  { id: 'query', ru: 'Query', en: 'Query', chapter: 'context', whyRu: 'Token должен сформулировать, какую информацию ищет.', whyEn: 'A token must express what information it seeks.', intuitionRu: 'Query — вектор запроса текущей позиции.', intuitionEn: 'A Query is the current position request vector.', related: ['key', 'value', 'attention'] },
  { id: 'key', ru: 'Key', en: 'Key', chapter: 'context', whyRu: 'Каждая позиция должна описать доступную информацию.', whyEn: 'Each position must describe available information.', intuitionRu: 'Key сопоставляется с Query.', intuitionEn: 'A Key is matched against a Query.', related: ['query', 'value', 'attention'] },
  { id: 'value', ru: 'Value', en: 'Value', chapter: 'context', whyRu: 'После совпадения нужна переносимая информация.', whyEn: 'Matched positions need information to carry.', intuitionRu: 'Value — содержимое, смешиваемое attention weights.', intuitionEn: 'A Value is content blended by attention weights.', related: ['query', 'key', 'attention'] },
  { id: 'softmax', ru: 'Softmax', en: 'Softmax', chapter: 'context', whyRu: 'Scores нужно превратить в нормированные веса.', whyEn: 'Scores must become normalized weights.', intuitionRu: 'Softmax делает значения положительными и суммой 1.', intuitionEn: 'Softmax makes values positive and sum to 1.', formal: 'softmax(zᵢ)=eᶻⁱ/Σⱼeᶻʲ', related: ['attention', 'logits'] },
  { id: 'attention', ru: 'Attention', en: 'Attention', chapter: 'context', whyRu: 'Состояние token должно использовать релевантный контекст.', whyEn: 'A token state must use relevant context.', intuitionRu: 'Attention взвешенно смешивает Values по сходству Query и Keys.', intuitionEn: 'Attention blends Values by Query-Key similarity.', formal: 'softmax(QKᵀ/√dₖ)V', moduleId: 'attention-module', related: ['query', 'key', 'value'], replay: 'c6-experiment' },
  { id: 'multi-head-attention', ru: 'Multi-Head Attention', en: 'Multi-Head Attention', chapter: 'context', whyRu: 'Одновременно существуют разные типы связей.', whyEn: 'Different relation types exist simultaneously.', intuitionRu: 'Несколько heads изучают разные проекции контекста.', intuitionEn: 'Multiple heads learn different context projections.', moduleId: 'multi-head-attention', related: ['attention', 'transformer-block'] },
  { id: 'rmsnorm', ru: 'RMSNorm', en: 'RMSNorm', chapter: 'block-assembly', whyRu: 'Scale состояния меняется между слоями.', whyEn: 'State scale changes across layers.', intuitionRu: 'RMSNorm стабилизирует средний квадрат координат.', intuitionEn: 'RMSNorm stabilizes root-mean-square scale.', moduleId: 'rmsnorm', related: ['residual', 'transformer-block'] },
  { id: 'residual', ru: 'Residual stream', en: 'Residual stream', chapter: 'block-assembly', whyRu: 'Преобразование не должно стирать исходный сигнал.', whyEn: 'A transformation should not erase the original signal.', intuitionRu: 'Residual path прибавляет изменение к прежнему состоянию.', intuitionEn: 'A residual path adds a change to the previous state.', formal: 'x ← x + f(x)', moduleId: 'residual-stream', related: ['rmsnorm', 'swiglu'] },
  { id: 'swiglu', ru: 'SwiGLU', en: 'SwiGLU', chapter: 'block-assembly', whyRu: 'Каждой позиции нужно нелинейное преобразование признаков.', whyEn: 'Each position needs a nonlinear feature transform.', intuitionRu: 'SwiGLU использует обучаемый gate для потока признаков.', intuitionEn: 'SwiGLU uses a learned gate over a feature stream.', moduleId: 'swiglu', related: ['activation', 'transformer-block'] },
  { id: 'transformer-block', ru: 'Transformer block', en: 'Transformer block', chapter: 'block-assembly', whyRu: 'Attention и FFN должны работать как повторяемая единица.', whyEn: 'Attention and FFN need a repeatable unit.', intuitionRu: 'Block чередует contextual mixing и per-token processing.', intuitionEn: 'A block alternates contextual mixing and per-token processing.', moduleId: 'transformer-blocks', related: ['attention', 'rmsnorm', 'residual'], replay: 'c7-experiment' },
  { id: 'causal-mask', ru: 'Causal mask', en: 'Causal mask', chapter: 'language-model', whyRu: 'При обучении нельзя видеть правильное будущее.', whyEn: 'Training must not reveal the correct future.', intuitionRu: 'Mask закрывает tokens справа от текущей позиции.', intuitionEn: 'The mask hides tokens to the right of the current position.', moduleId: 'causal-mask', related: ['next-token', 'attention'] },
  { id: 'next-token', ru: 'Следующий токен', en: 'Next token', chapter: 'language-model', whyRu: 'Языковой модели нужна самосогласованная цель.', whyEn: 'A language model needs a self-contained objective.', intuitionRu: 'Каждая позиция предсказывает следующий element последовательности.', intuitionEn: 'Every position predicts the next sequence element.', related: ['causal-mask', 'lm-head'] },
  { id: 'logits', ru: 'Logits', en: 'Logits', chapter: 'language-model', whyRu: 'Модель сначала выдаёт ненормированные scores.', whyEn: 'A model first emits unnormalized scores.', intuitionRu: 'Logits — значения до softmax.', intuitionEn: 'Logits are values before softmax.', related: ['softmax', 'lm-head'] },
  { id: 'lm-head', ru: 'LM Head', en: 'LM Head', chapter: 'language-model', whyRu: 'Contextual state нужно проецировать на vocabulary.', whyEn: 'A contextual state must project onto the vocabulary.', intuitionRu: 'LM head выдаёт один logit для каждого token.', intuitionEn: 'The LM head emits one logit per token.', moduleId: 'lm-head', related: ['logits', 'next-token'] },
  { id: 'sampling', ru: 'Sampling', en: 'Sampling', chapter: 'language-model', whyRu: 'Distribution нужно превратить в выбранный token.', whyEn: 'A distribution must become a selected token.', intuitionRu: 'Sampling выбирает продолжение с управляемой случайностью.', intuitionEn: 'Sampling chooses a continuation with controlled randomness.', moduleId: 'sampling-engine', related: ['temperature', 'logits'] },
  { id: 'temperature', ru: 'Temperature', en: 'Temperature', chapter: 'language-model', whyRu: 'Нужен контроль разнообразия генерации.', whyEn: 'Generation diversity needs control.', intuitionRu: 'Малая temperature заостряет, большая уплощает distribution.', intuitionEn: 'Low temperature sharpens and high temperature flattens a distribution.', formal: 'softmax(logits / T)', related: ['sampling', 'softmax'] },
  { id: 'dataset', ru: 'Dataset', en: 'Dataset', chapter: 'training-console', whyRu: 'Модель учится только на доступных примерах.', whyEn: 'A model learns only from available examples.', intuitionRu: 'Dataset — версия и состав обучающих текстов.', intuitionEn: 'A dataset is the versioned collection of training texts.', related: ['validation', 'batch'] },
  { id: 'validation', ru: 'Validation', en: 'Validation', chapter: 'training-console', whyRu: 'Train loss не доказывает перенос на новые данные.', whyEn: 'Training loss does not prove transfer to new data.', intuitionRu: 'Validation измеряет модель на неиспользованных примерах.', intuitionEn: 'Validation measures the model on held-out examples.', related: ['dataset', 'overfitting'] },
  { id: 'batch', ru: 'Batch', en: 'Batch', chapter: 'training-console', whyRu: 'Обрабатывать весь dataset за шаг слишком дорого.', whyEn: 'Processing the whole dataset per step is too expensive.', intuitionRu: 'Batch — подмножество примеров для одного update.', intuitionEn: 'A batch is a subset of examples for one update.', related: ['optimizer', 'dataset'] },
  { id: 'optimizer', ru: 'Optimizer', en: 'Optimizer', chapter: 'training-console', whyRu: 'Raw gradient недостаточно устойчив для сложной модели.', whyEn: 'Raw gradients are not stable enough for a complex model.', intuitionRu: 'Optimizer преобразует gradients в обновления weights.', intuitionEn: 'An optimizer converts gradients into weight updates.', related: ['adamw', 'learning-rate'] },
  { id: 'adamw', ru: 'AdamW', en: 'AdamW', chapter: 'training-console', whyRu: 'Параметры имеют разные масштабы и историю gradients.', whyEn: 'Parameters have different scales and gradient histories.', intuitionRu: 'AdamW адаптирует шаг и отдельно применяет weight decay.', intuitionEn: 'AdamW adapts the step and applies weight decay separately.', related: ['optimizer', 'learning-rate'] },
  { id: 'checkpoint', ru: 'Checkpoint', en: 'Checkpoint', chapter: 'training-console', whyRu: 'Долгий training run нельзя терять.', whyEn: 'A long training run must not be lost.', intuitionRu: 'Checkpoint сохраняет config, weights, step и metadata.', intuitionEn: 'A checkpoint stores config, weights, step, and metadata.', related: ['dataset', 'optimizer'] },
  { id: 'overfitting', ru: 'Переобучение', en: 'Overfitting', chapter: 'training-console', whyRu: 'Модель может запомнить train и ухудшиться на новых данных.', whyEn: 'A model may memorize training data and worsen on new data.', intuitionRu: 'Overfitting виден как разрыв train и validation loss.', intuitionEn: 'Overfitting appears as a train-validation loss gap.', related: ['validation', 'dataset'] },
  { id: 'language-model', ru: 'Языковая модель', en: 'Language model', chapter: 'my-llm', whyRu: 'Все механизмы должны дать наблюдаемый языковой результат.', whyEn: 'All mechanisms must produce an observable language result.', intuitionRu: 'Language model оценивает и генерирует token sequences.', intuitionEn: 'A language model scores and generates token sequences.', moduleId: 'sampling-engine', related: ['transformer-block', 'next-token', 'checkpoint'] },
];

export const CONCEPT_CATALOG = Object.fromEntries(seeds.map((value) => {
  const concept = seed(value);
  return [concept.id, concept];
})) as Record<string, KnowledgeConcept>;

export const CONCEPT_ORDER = seeds.map(({ id }) => id);

export const CONCEPT_GRAPH: ConceptGraphEdge[] = seeds.flatMap(({ id, related = [] }) => related
  .filter((relatedId) => seeds.some((candidate) => candidate.id === relatedId))
  .map((relatedId) => ({ from: id, to: relatedId })));

export function getConcept(id: string): KnowledgeConcept | undefined {
  return CONCEPT_CATALOG[id];
}
